### ISSUE TITLE
Notify users after 55 minutes of inactivity that they will be logged out in 5 minutes

### ISSUE THREAD

**Issue by carlykube** [carlykube/VirtualScada#29]

**Comment by kolengue** [comment]
55 minutes is possibly the 5 minute log out idk what controls that ... seems too long i think it does 20 seconds now. still need this to look better but this is done functionality wise
![screen shot 2015-04-12 at 21 35 40](https://cloud.githubusercontent.com/assets/5254174/7109072/f648023c-e15b-11e4-867a-66d63a2c4509.png)

**Comment by kolengue** [comment]
dialogue box can be found for formatting in app.blade.php @aheerwagen  @poshprogrammer
