### ISSUE TITLE
Make the permissions page look pretty

### ISSUE THREAD

**Issue by carlykube** [carlykube/VirtualScada#33]
permissions.blade.php

You can get there by clicking on a project and then clicking "Permissions"

**Comment by poshprogrammer** [comment]
Changed the permissions page, but there is an tiny issue where each edit has it's own save button (e.g. each row of the table of users with permissions has a save button). I've been trying for a while to fix it within the form, but every time I try something it breaks it. I'll come back to it, but for now at least it's better than before and works correctly. The way it should be is one "Save All" at the bottom of that half.
