### ISSUE TITLE
Allow users to create project with default settings (UI)

### ISSUE THREAD

**Issue by carlykube** [carlykube/VirtualScada#9]
Maybe have one connected RTU and HMI?

**Comment by Distinc-T** [comment]
So this is closed - but do we have the UI for this yet?

**Comment by socratariat** [comment]
oh I thought what we had was what we wanted

**Comment by carlykube** [comment]
I think the UI for this is done-ish. Unless we're going to combine the  separate "User Dashboard" pages? see #11

**Comment by poshprogrammer** [comment]
I moved this page over to the main dashboard since, with the way it is currently implemented, you're only entering in a name. This way, if we decide to change it to drop down for number of RTUs/HMIs, it can still be done from the main dashboard.
